//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultations()
        {
            this.Prescriptions = new HashSet<Prescriptions>();
            this.ResultatsExamens = new HashSet<ResultatsExamens>();
        }
    
        public int ConsultationId { get; set; }
        public int RendezVousId { get; set; }
        public int MedecinId { get; set; }
        public string Diagnostic { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateConsultation { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual RendezVous RendezVous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescriptions> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultatsExamens> ResultatsExamens { get; set; }
    }
}
