//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABMED.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CabinetEntities : DbContext
    {
        public CabinetEntities()
            : base("name=CabinetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultations> Consultations { get; set; }
        public virtual DbSet<Disponibilites> Disponibilites { get; set; }
        public virtual DbSet<Prescriptions> Prescriptions { get; set; }
        public virtual DbSet<RendezVous> RendezVous { get; set; }
        public virtual DbSet<ResultatsExamens> ResultatsExamens { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
