//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescriptions
    {
        public int PrescriptionId { get; set; }
        public int ConsultationId { get; set; }
        public string Medicament { get; set; }
        public string Posologie { get; set; }
    
        public virtual Consultations Consultations { get; set; }
    }
}
