//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescriptions
    {
        public int PrescriptionId { get; set; }
        public int ConsultationId { get; set; }
        public string Medicament { get; set; }
        public string Posologie { get; set; }
    
        public virtual Consultations Consultations { get; set; }
    }
}
