//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendezVous
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RendezVous()
        {
            this.Consultations = new HashSet<Consultations>();
        }
    
        public int RendezVousId { get; set; }
        public int PatientId { get; set; }
        public int MedecinId { get; set; }
        public System.DateTime DateHeureDebut { get; set; }
        public System.DateTime DateHeureFin { get; set; }
        public string Statut { get; set; }
        public string Motif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultations> Consultations { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
