//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultatsExamens
    {
        public int ResultatId { get; set; }
        public int ConsultationId { get; set; }
        public string TypeExamen { get; set; }
        public System.DateTime DateExamen { get; set; }
        public string Fichier_URL { get; set; }
        public string CommentairesMedecin { get; set; }
    
        public virtual Consultations Consultations { get; set; }
    }
}
