//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABMED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultatsExamens
    {
        public int ResultatId { get; set; }
        public int ConsultationId { get; set; }
        public string TypeExamen { get; set; }
        public System.DateTime DateExamen { get; set; }
        public string Fichier_URL { get; set; }
        public string CommentairesMedecin { get; set; }
    
        public virtual Consultations Consultations { get; set; }
    }
}
